export interface AlternativeInput {
  id: number;
  text: string;
  userPros?: string[];
  userCons?: string[];
}

export type DecisionFramework = 'General' | 'Christianity' | 'Muslim' | 'Hedonistic' | 'Efficient';

export interface DecisionInput {
  situation: string; // Context
  problem: string; // Specific question/problem
  values: string[]; // User selected values (max 3)
  alternatives: AlternativeInput[];
  framework: DecisionFramework;
}

export interface EvaluatedAlternative {
  id: number;
  originalText: string;
  title: string; // A short summary title generated by AI
  score: number; // 0-100
  outcomes: string[]; // New: Specific bullet points for likely outcomes
  reasoning: string; // Detailed narrative analysis
  pros: string[];
  cons: string[];
}

export interface DecisionAnalysis {
  bestChoiceId: number;
  executiveSummary: string;
  results: EvaluatedAlternative[];
}

export interface FollowUpAdvice {
  steps: string[];
  advice: string;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}

export enum AppState {
  INPUT = 'INPUT',
  LOADING = 'LOADING',
  RESULTS = 'RESULTS',
  ERROR = 'ERROR',
}